services:
  - type: web
    name: aivana
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: TO_BE_REPLACED_IN_RENDER_DASHBOARD
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: TO_BE_REPLACED_IN_RENDER_DASHBOARD
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: TO_BE_REPLACED_IN_RENDER_DASHBOARD
      - key: GROQ_API_KEY
        value: TO_BE_REPLACED_IN_RENDER_DASHBOARD
